### ISSUE TITLE
Completely broken

### ISSUE THREAD

**Issue by jwilk** [SirCmpwn/evilpass#4]
```console
$ python -c 'from evilpass import check_pass; check_pass("password", "email address", "username")'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "evilpass/__init__.py", line 54
SyntaxError: Non-ASCII character '\xe2' in file evilpass/__init__.py on line 54, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
```
Hmm, okay, maybe it's for Python 3? Let's try it:
```console
$ python3 -c 'from evilpass import check_pass; check_pass("password", "email address", "username")'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/jwilk/evilpass/evilpass/__init__.py", line 112
    upper = False, lower = False, number = False
               ^
SyntaxError: can't assign to keyword
```
Huh?

Tested with git master (b60ec36729b7fb79af7f66b10ccc82721bceafbf).

**Comment by Ninja3047** [comment]
Fixed here https://github.com/SirCmpwn/evilpass/pull/3
You can try it with my fork for now https://github.com/Ninja3047/evilpass

**Comment by SirCmpwn** [comment]
Forgot to push my fixes last night. Apologies!
